# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Reciplease' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reciplease
  pod 'Alamofire'
  pod 'SharkORM'
  pod 'SwiftyJSON', '~> 4.0'

  target 'RecipleaseTests' do
        inherit! :search_paths
    end

end
